[package]
name = "originweave-core"
description = "OriginWeave core contracts."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lib]
path = "src/root.rs"

[dependencies]

[lints]
workspace = true
